### ISSUE TITLE
Support for koa 2.x

### ISSUE THREAD

**Issue by jericho2** [nfl/react-wildcat#195]
Are y'all planning to support koa 2.x in the wildcat packages? We cannot upgrade our middleware because of this:
https://github.com/nfl/react-wildcat/blob/dcd2b494dd3d6000efd0a5c98a8a97131ca8ca9f/packages/react-wildcat/package.json#L24

Thank you,
Yan

**Comment by jamsea** [comment]
@jericho2 koa 2.x isn't on our roadmap, but we're open to review pull requests! Are there any significant performance wins in koa 2?
