### ISSUE TITLE
How to tack on some extra server-only routes?

### ISSUE THREAD

**Issue by staxmanade** [nfl/react-wildcat#68]
Hey, been playing with the project for a bit and so far it's mostly going great...

I've mostly rewritten a little toy project's server/client page rendering using react-wildcat. However the app's data is currently being pulled in via an AJAX call to the production endpoint.

I'd like to take a couple express JSON API routes that I have and would like to now bring them into the react-wildcat dev project.

I see that both client and server are configured load "main.js". How would you suggest I go about tacking on some API express routes?

Thinking I'll need to break server/client root json - but not how that should interact with wildcat as well as how do I get access to express in the server to add custom api routes etc...

Thoughts? 

This (which starts the server) doesn't expose the result of the `.start()`. (But also haven't yet found where this package gets initialized from...
https://github.com/nfl/react-wildcat/blob/master/packages/react-wildcat/main.js#L12

**Comment by doctyper** [comment]
Not sure I totally grok the question, but you can specify unique entry points for either the [client](https://github.com/nfl/react-wildcat/blob/master/example/wildcat.config.js#L72) and/or [server](https://github.com/nfl/react-wildcat/blob/master/example/wildcat.config.js#L85). Does that help with your issue?

**Comment by staxmanade** [comment]
Is there an example of how to do that on the server?

I'm not sure how to tie in and configure a custom route...

**Comment by doctyper** [comment]
Hm, no there's no example. We haven't had the need to handle dynamic API data, all of our data comes from external API endpoints. I'm not sure Wildcat is set up for that yet, but let me know if you tinker with it.

**Comment by doctyper** [comment]
At a high-level, I'm thinking we'll need to expose a middleware config option through `wildcat.config.js`. Then you could specify custom Koa middleware such as [koa-router](https://github.com/alexmingoia/koa-router) to provide the functionality you're looking for.

**Comment by staxmanade** [comment]
Ok, I tried hacking on it a bit (but sadly not getting the expected result - yet).

In my `wildcat.config.js` I added the `onAppConfiguration` here:

```
        // config options for the app server
        appServer: {
            // One of http2 | https | http
            protocol: "http2",

            hostname: "localhost",

            // App server port
            port: getPort(process.env.PORT, 3000),

            onAppConfiguration: (app) => {
                console.log("onAppConfiguration run:", app);
                app.use(route.all('/jj-test', function *(){
                    this.body = 'Hello World';
                }));
            },
```

Then in `examples/node_modules/react-wildcat/src/server.js` I hacked the following into about [this location](https://github.com/nfl/react-wildcat/blob/master/packages/react-wildcat/src/server.js#L131)

```
            if(typeof appServerSettings.onAppConfiguration === "function") {
                try {
                    appServerSettings.onAppConfiguration(app);
                } catch(err) {
                    console.error(err);
                }
            }
```

I see my console.log's so I know the code is getting executed. But I'm still getting a 404's at the `/jj-test` route and not quite sure why (still debugging)...

Any guidance on a more preferred approach?

**Comment by doctyper** [comment]
The following works for me:

In `react-wildcat/src/server.js`, on or before [line 109](https://github.com/nfl/react-wildcat/blob/master/packages%2Freact-wildcat%2Fsrc%2Fserver.js#L109):

```js
            if (typeof appServerSettings.onAppConfiguration === "function") {
                try {
                    appServerSettings.onAppConfiguration(app);
                } catch (err) {
                    console.error(err);
                }
            }

```

Then:

1. `npm link react-wildcat` in `example`
2. `npm install koa-router` in `example`
3. Add the following to `example/wildcat.config.js`, on or around [line 124](https://github.com/nfl/react-wildcat/blob/master/example%2Fwildcat.config.js#L124):

```js
            onAppConfiguration: (app) => {
                console.log("onAppConfiguration run:", app);

                router.get("/jj-test", function *() {
                    this.body = "Hello World";
                });

                app.use(router.routes());
            }
```

Make sure to `const router = require("koa-router")();` at the top of `wildcat.config.js`

**Comment by staxmanade** [comment]
Ahh my issue was the order of where I hook the `app.use(...` - thanks!

Does it make sense to use this local "hack"? Is it in line with you're vision of how this should/could be accomplished? (Basically, would it be worth putting together a pull request?)

**Comment by doctyper** [comment]
I definitely think a middleware hook is a good idea. Just haven't had time to work on it. Feel free to PR, but I had a different idea on how to expose this through wildcat.config.js. Maybe a `middleware` property that takes an array of middleware functions to bootstrap?

**Comment by staxmanade** [comment]
Closing in favor of #71
