### ISSUE TITLE
Exceptions on startup not reported

### ISSUE THREAD

**Issue by staxmanade** [nfl/react-wildcat#70]
I noticed that if an exception were raised within [`server.js`](https://github.com/nfl/react-wildcat/blob/master/packages/react-wildcat/src/server.js#L131), the error is not logged to the console or easily visible and it appears to just hang the process on startup.

I noticed that the caller to `.start()` [here](https://github.com/nfl/react-wildcat/blob/master/packages/react-wildcat/staticServer.js#L9) does not use a `.catch(...)` from the returned promise, however the function doesn't always return a promise so I'm not sure what the intent is there (with the clustering etc..).

Thoughts?

**Comment by doctyper** [comment]
`start` should always return a Promise. If you're seeing otherwise that's a legitimate bug. Can you provide a sample where this can happen? I'll work on reproducing this and adding a test for it.

**Comment by doctyper** [comment]
Ah, I see what you mean about using clusters. I'll dig into it.
