### ISSUE TITLE
New Setup Fails

### ISSUE THREAD

**Issue by staxmanade** [nfl/react-wildcat#73]
Hey @doctyper,

I'm trying to do a deploy to Heroku and ran into some trouble - when I went back to my current solution (removed the `node_modules` folder and tried to re-setup by running `make install` I get the following. The same reproduces if I freshly clone `react-wildcat` and try to run `make install`.
 
```
~/code/temp/react-wildcat> make install
./shell/clean.sh
./shell/clean-example.sh
npm install --silent
make: *** [bootstrap] Error 1
```

if I `npm install` (without the `--silent`) flag I get:

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: react-wildcat-prefetch@'>=1.1.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-beta5","1.0.0-beta4","1.0.0-beta7","1.0.0-beta6","1.0.0-beta1","1.0.0-beta3","1.0.0-beta2","1.0.0-rc4","1.0.0-rc3","1.0.0-rc2","1.0.0-rc1","1.0.0-beta9","1.0.0-beta10","1.0.0-rc8","1.0.0-beta8","1.0.0-rc7","1.0.0","1.0.0-rc6","1.0.1","1.0.0-rc5"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'wildcat'
npm ERR! notarget
```

**Comment by potench** [comment]
Hey @staxmanade - I notice you're using nose 4.2.4 but the .node_version is expecting 4.2.1. Might need to try downgrading?

**Comment by doctyper** [comment]
Hm. Weird, it's reporting that `react-wildcat-prefetch@1.1.0` is not found, but it is [published and available](https://www.npmjs.com/~nfl).

Are you deploying your own project to Heroku? If so you probably should not be running `make install`, those scripts are for setting up a dev environment to work on `react-wildcat`. You should be fine simply running `npm install` in your project's root.

**Comment by staxmanade** [comment]
The make install was my local Dev env.

The heroku step was a postinstall step to npm install/jspm install. (I had a strange issue there and wanted to see if it reproduce locally) so I deleted my node_modules folder and re-ran make install.

I'll give the node downgrade a try when I get back to it.

**Comment by doctyper** [comment]
can you gist up the full log? It's possible that some step before this is causing the issue.

**Comment by staxmanade** [comment]
Sorry for the false alarm... Had an issue with my `.npmrc` file causing connectivity issues to NPM...
