### ISSUE TITLE
Parameterized routes hang on first try?

### ISSUE THREAD

**Issue by staxmanade** [nfl/react-wildcat#77]
Hey,

Something interesting I've been seeing while playing with a couple routes that have parameters.

On initial server-start and first request appeared to just hang. Sometimes I would have to refresh the browser 2-3 times before I would see the route start working.

One thing I noticed was that in the [following commit](https://github.com/nfl/react-wildcat/commit/5fd28433bc5ad9e3eaecc830d2feda26876d24be) these hangs turned from hangs into  errors at the console. (So before-hand the hangs must have just been swallowed errors) - but now I'm not exactly sure why I'm getting the error on the first or second/third request - but after the server has "warmed up" everything seems to run fine again.

## Error printed to the console:

```
[0] TypeError: Invalid attempt to destructure non-iterable instance
[0]     at eval (https://localhost:4000/jspm_packages/npm/babel-runtime@5.8.35/helpers/sliced-to-array.js:39:13)
[0]     at ensureResult (https://localhost:4000/public/routes/ViewGame/routes.js:25:21)
[0]     at normalizedImportsError (https://localhost:4000/jspm_packages/npm/react-wildcat-ensure@1.0.0/dist/index.js:68:16)
[0]     at process._tickCallback (node.js:368:9)
```

## Example of how I'm setting up a route...

In a folder `example/src/routes/ViewGame` I have the following

### `routes.js`
```
import ensure from "react-wildcat-ensure";

// React router route
export const path = "/view-game/:gameId";

// Lazy loaded components
export function getComponent(location, cb) {
    ensure(["./ViewGame.js"], module, function ensureResult(err, [module]) {
        return cb(err, module);
    });
}
```

### `ViewGame.js`
```
import React from "react";
import Helmet from "react-helmet";
import 'isomorphic-fetch';

export default class ViewGame extends React.Component {
    render() {
        return <div>Hello</div>;
    }
}
```

I've extended `example/src/ApplicationRoutes.js` with the following

```diff
import React from "react";
import {IndexRoute, Redirect, Route} from "react-router";

import Application from "./components/Application/Application.js";

import * as indexExampleRoutes from "./routes/IndexExample/routes.js";
+import * as viewGameRoutes from "./routes/ViewGame/routes.js";
-import * as errorExampleRoutes from "./routes/ErrorExample/routes.js";
-import * as flexboxExampleRoutes from "./routes/FlexboxExample/routes.js";
-import * as helmetExampleRoutes from "./routes/HelmetExample/routes.js";
-import * as prefetchExampleRoutes from "./routes/PrefetchExample/routes.js";

var Routes = (
    <Route path="/" component={Application}>
        <IndexRoute {...indexExampleRoutes} />

+        <Route {...viewGameRoutes} />
-        <Route {...errorExampleRoutes} />
-        <Route {...flexboxExampleRoutes} />
-        <Route {...helmetExampleRoutes} />
-        <Route {...prefetchExampleRoutes} />
-
-       <Redirect from="/redirect" to="/flexbox-example" />
    </Route>
);

export default Routes;
```

Have you seen this before? Could I be implementing parameterized routes wrong? Any thoughts?

**Comment by doctyper** [comment]
Try the `ensure` callback without the array wrapper:

```js
export function getComponent(location, cb) {
    ensure("./ViewGame.js", module, function ensureResult(err, module) {
        return cb(err, module);
    });
}
```

**Comment by staxmanade** [comment]
That was helpful - the destructuring error was masking a separate error. (not sure why it worked after trying to run it a few times) but this un-blocks me to dig further. Thanks
