### ISSUE TITLE
Provide a stack trace when transpiling errors occur

### ISSUE THREAD

**Issue by alanmulhall** [nfl/react-wildcat#83]
I'm seeing this error occur `Error: self is not defined` but there is no stack trace to help find out where the error is occurring, is it possible to also display the stack trace with the error message?

**Comment by staxmanade** [comment]
@alanmulhall I ran into that as well.

My quick/hack was to add the following to `Application.js` - the problem is as referenced in the below comments with isomorphic-fetch.

```
// hack to fix
// https://github.com/matthew-andrews/isomorphic-fetch/issues/59
// https://github.com/matthew-andrews/isomorphic-fetch/pull/63
global.self = global.self || global;
```

But also agree that the stacktrace would be more useful in the general error case.

**Comment by doctyper** [comment]
Here's a sample BSOD with #84:

![stack-trace](https://cloud.githubusercontent.com/assets/6960/13828423/ae15ebf4-eb7e-11e5-9a28-c4001fd4716c.png)

**Comment by staxmanade** [comment]
nice @doctyper

**Comment by alanmulhall** [comment]
@staxmanade - thanks, good suggestion

**Comment by alanmulhall** [comment]
:+1:
